services:
  app:
    image: nancy1xn/screening-rag:v1.0
    environment:
      QDRANT_DOMAIN: qdrant
      MYSQLDB_HOST: sql
      MYSQLDB_USER: ${MYSQLDB_USER}
      MYSQLDB_PW: ${MYSQLDB_PW}
      MYSQLDB_DATABASE: ${MYSQLDB_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      qdrant:
        condition: service_started
      sql:
        condition: service_healthy

    command: screening-rag init --keywords 'JP Morgan Financial Crime, Binance Financial Crime' --amount 3

  
  qdrant:
    image: qdrant/qdrant
    volumes:
     - qdrant_data:/qdrant/storage
  
  
  sql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PW}

    volumes:
     - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    

volumes:
  qdrant_data:
  mysql_data:  

