services:
  app:
    image: nancy1xn/screening-rag:v1.0
    environment:
      QDRANT_DOMAIN: qdrant
      MYSQLDB_HOST: sql
      MYSQLDB_USER: ${MYSQLDB_USER}
      MYSQLDB_PW: ${MYSQLDB_PW}
      MYSQLDB_DATABASE: ${MYSQLDB_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    depends_on:
      qdrant:
        condition: service_started
      sql:
        condition: service_healthy

    command: screening-rag init --keywords 'JPMorgan Chase & Co. Financial Crime, Binance Holdings Ltd. Financial Crime, Deutsche Bank Financial Crime' --amount 25